### ISSUE TITLE
[SUGGESTION] I have translated the Chinese translation file of your module and have submitted it.

### ISSUE THREAD

**Issue by charmaznable** [StavWasPlayZ/Genshin-Instruments#11]
I have translated the Chinese translation file of your module and have submitted it.
I'm not sure if the submission is correct, but I can provide the documents. Translate English files using the latest version of the module into Chinese.
[zh_cn.json](https://github.com/StavWasPlayZ/Genshin-Instruments/files/13696794/zh_cn.json)

**Comment by StavWasPlayZ** [comment]
Will take that as a yes, lol
