### ISSUE TITLE
[QUESTION] Confirmation on Chinese translation

### ISSUE THREAD

**Issue by StavWasPlayZ** [StavWasPlayZ/Genshin-Instruments#14]
Quick issue on behalf of a new translation key for the v3.4.1 update.  
Please confirm that the translation for "Sensitivity" in Chinese is indeed "灵敏度".

Context: MIDI input sensitivity

Thanks!

@SteveNotSet

**Comment by SteveNotSet** [comment]
It's correct.

**Comment by StavWasPlayZ** [comment]
Thank you!
