### ISSUE TITLE
New Genshin Instrument Texture (Nightwind Horn)

### ISSUE THREAD

**Issue by GenMode** [StavWasPlayZ/Genshin-Instruments#15]
here's the textures you requested
![draft#3](https://github.com/user-attachments/assets/b80a1a01-0fc8-49f0-ac2e-f9da175e66ea)
![draft#2](https://github.com/user-attachments/assets/d43555d2-a87a-4fa0-9cbd-7f2b559c309a)

**Comment by StavWasPlayZ** [comment]
Looks incredible! Thank you!!
