### ISSUE TITLE
[QUESTION] Still Updating Mod or not

### ISSUE THREAD

**Issue by Secondyou** [StavWasPlayZ/Genshin-Instruments#18]

**Comment by StavWasPlayZ** [comment]
Hey, I really don't understand the question here. I quite literally pushed an update a week or so ago?

You can also see my way-too-active commit history here and in EMI, currently to bring modern version support for both mods.

I also must note that I unfortunately have covid, and my energy is not at its best. I try to maintain balance between studies, recovery, and this side project of mine.

Yet I still do all this work.

Still, mod development takes time. Especially when Genshin Instruments is an API, and I ALSO maintain its sidemod plugin all the same.

Again, I don't understand where this question is coming from or why. Anything specific you're looking for..?

If you're seeking for modern version support, expect a 1.20.6 port about tomorrow or so ig? Mojang changed a lot of core, technical elements in 1.20.5, so this process is not instantaneous whatsoever. Same applies to 1.21.x.

**Comment by StavWasPlayZ** [comment]
Also, make sure you follow the CurseForge or Modrinth version channels, and that you're not using some unofficial or pirated site for downloading the mod.

https://www.curseforge.com/minecraft/mc-mods/genshin-instruments  
https://modrinth.com/mod/genshin-instruments/versions

**Comment by Secondyou** [comment]
okay i think my question is confusing btw so

i just want to check if still updating or not into modern versions of Minecraft

**Comment by StavWasPlayZ** [comment]
As I said, yes.

Hoping to push a release all the way up to 1.21 & its patches by this week or the next. 

Again, not gonna be instantaneous. I'm not as physically capable at the moment.

This does not mean,however, that this mod is abandoned, or "not updated anymore".

...You should probably ask questions a bit more straightforward going forward, though..-

**Comment by Secondyou** [comment]
thanks for info
