### ISSUE TITLE
[Request] Fabric 1.19.2 Port.

### ISSUE THREAD

**Issue by whatamaniac** [StavWasPlayZ/Genshin-Instruments#5]
Hello,
        I've been working on a modpack from the past 4-5 months... which is for a creators only SMP (For people who love to do creative things in minecraft and are also 🎥 streamers/content creators). and i've always wanted to have something related to musical instruments🪗. I love genshin music and i wanted it in my modpack so for first i thought of making a resource pack to replace minecraft bg music and when i saw your mod i was SOO SOO SOO FKing Happy😊(One of my mods showed it to me).. I was literally addicted to it. But i was little bumped knowing that it's not available for Fabric 1.19.2 as my modpack is on that version. Consider this only as a small request... as i myself know how much time consuming and difficult it is to commit to downgrade to older versions. If it is possible i would really love to help you...😅i don't know coding that much. But if there's anything related to playtesting/bug testing/incompatibility checks, feel free to dm me and i'll be there to help (i know it's not easy for a solo dev to port it just based on a single persons request). I am pretty sure LOTS of people and modded community will Love it and lots of other Modapck Devs will include it in their modpack. I'll do my Best to Feature it and to Promote it as much i can cuz i definelty believe lots of people will love it. =]💖

**Comment by StavWasPlayZ** [comment]
Hey there! Thank you so, so much for your comment! You don't even know how much it means to me 🥹💔

Actually, I have been planning to begin backporting the mod anyways starting tomorrow! I can't promise to make it all the way to 1.19.2, and heck — let alone 1.20; But I was able to deliver on making the Fabric port, so fingers crossed that I'd also succeed downgrading it from there 😭

I highly appreciate the call for assistance! However, I would like to stay on the confines of my fellow friends as playtestsers, since I always host my test servers locally. It would thus put me under risk to share my private network and IP address...


All I can say is that you should stay tuned during the next couple of weeks or so. I'll try my best and update you under this issue thread.

Thank you so much for your support!
Enjoy thy plays 🪇

**Comment by StavWasPlayZ** [comment]
It has been done!
https://github.com/StavWasPlayZ/Genshin-Instruments-Fabric/releases/tag/1.19.2-2.8

Please report any issues that may arise in the Fabric repository.

**Comment by whatamaniac** [comment]
Hey, Just wanted to say Thank you very very very much💖. I thought it'll take time but 2 days xDD Daamnn that was quick... Even i wanna learn some coding skills now. But anyways thnk you again... I'll try my best to promote this mod and i'll also ask my friends to promote it aswell on their streams whenever i release the SMP... cuz i believe it has alot of potential. Keep doing what you're doing. I hope we'll see more such beautiful mods in furture aswell🤗Peace

**Comment by StavWasPlayZ** [comment]
You're very much welcome. Hope y'all enjoy!


> Even i wanna learn some coding skills now

Start with C#!! Java is messy and so will it mess you up. Judging from experience 😅 (C# ≈ Java)
Minecraft, as a whole, is coded in a very weird way, and I wouldn't recommend going straight to it. I'd say go this route:


C# -> Java -> HTML/CSS/JS (Web development kit, lean to use devtools!!) -> Any server framework (ASP.NET for C# is nice, or NodeJS for JavaScript) -> Forge modding -> Fabric if you wanna

Note that between each language you learn, you should make a small project with it. For instance:
- **C# & Java**: Build a console tool with C# or Java that'll help you... sort your books by a category (name, serial number and whatnot), or backup your driver, or make some fun "complete the story" and hangman games etc.
- **Webdev kit**: Make a nice portfolio to introduce yourself! A homepage that ascribes your "about me", some iframes to your YouTube or Instagram in a "Find me" page; go wield. Especially with design (CSS).
- **Server framework**: Mix em all up; make a blog website where the user must log in to post something nice (get inspirations from Facebook or a social media you like), user pages, and restricted pages (such that only logged in users or admins can access *x* page)
  - You might need SQL for that one (preferably MYSQL)


This route will guarantee you know all the basics of computer science and programming. Web-dev will also give you much more depth to networking and server-client relationships, and oh boy does Minecraft need some.

Also note that Fabric itself is literally just a mod loader, and maybe the Fabric API helps with some stuff here and there. That means that you'll have to manipulate the game itself (via Mixins and whatnot) to mostly behave as you wish. That is why I recommend getting started with Forge, as it is a whole blown API with immense amounts of features for devs.

At least that's my recommendation, lol.  
Good luck!!

**Comment by whatamaniac** [comment]
I always wanted to create a mod of own for my season of SMP and i didn't knew where to start from cuz i have alot of things pending which are lined up for this year (SMP work, Getting my Modpack ready as soon as Modrinth Launcher comes out, get back to uploading VODS etc) and when u have so many things lined up... i usually get lazy and don't understand where to begin from.

I actually needed someone to tell me what to do and how to proceed and You had to be that person for me. This was really helpfull. Thank you once again for guiding. I'll surely proceed with all of these as soon as i get all the lined up things sorted😊💖

**Comment by StavWasPlayZ** [comment]
Good luck with everything!

I will now be locking this conversation.  
Remember to report any issues to the [Fabric repository](https://github.com/StavWasPlayZ/Genshin-Instruments-Fabric/issues). You may also suggest a new feature / feature change under the `suggestion` label in this repository.

Yet again, thank you so much for your support!
