### ISSUE TITLE
Texture changes

### ISSUE THREAD

**Issue by GenMode** [StavWasPlayZ/Genshin-Instruments#9]
I've made some textures for the genshin instruments mod, what are your thoughts? Would you like to add these in the game?
![Screenshot 2023-09-15 230921](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/9fc89e75-37bc-4b46-9534-934a9e482e54)

**Comment by StavWasPlayZ** [comment]
WHAAAAATT??? AHHH I LOVE THEM SO MUCHH!!!!  
You are incredible!!! Yes, I would absolutely LOVE to implement those!

The colors are simply amazinggg!! And the Zither looks exceptionally awesome! Such a great representation!

Also an FYI, I asked my parents regarding which texture row is better (they have 0 experience with neither pixel art nor the Genshin instruments [...nor any musical instrument]), and they much perferred the lower one bahaha

I will, however, require your full consent and permission that both I and the public users can 100% use these assets both in-game and out (video showcases, logo etc.), just as they were used the latter all along.  
Of course, your work will absolutely *not* go uncredited 😄

And well, speaking of logo, I was thinking of the same one where the 3 dominant instruments are showcased but with the updated textures. However, if you're feeling fancy, you can suggest something else, too:
<img src="https://github.com/StavWasPlayZ/Genshin-Instruments/blob/master/src/main/resources/icon.png?raw=true" width="100">

Lastly, to keep things consistent, I will also ask that you may texture any new Genshin instrument to come in the future ahead (they come like once a year or so). Is that something you will be fine to do?

Lastly, tysm!! You really made my day! 😊


> P.S: Got a Ko-Fi or something I can both link to and use? 🙂

**Comment by GenMode** [comment]
I think your way of doing the logo is fine lol. Also I would be happy to texture the new instruments as well as the ones from your other mod like we discussed on PMC. I'm a fan of music mods so this is very fun for me as well lol. And yes you and the public have full consent to use these textures if they're relating to this mod

Here's the assets by the way:
![floral_zither](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/2c2a8b6b-8645-4737-a94d-761dc0aba8b8)
![glorious_drum](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/3b7f933d-fb4c-4fdf-8133-95c2a70fb04c)
![vintage_lyre](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/8ef53966-a48a-438e-b43c-d6842a089628)
![windsong_lyre](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/a26f59d0-3ebe-4546-acd9-80f7ef979d2f)

**Comment by StavWasPlayZ** [comment]
Thank you so much!

I have just committed your work, and expect it to be implemented around the 1.20.2 release; on the hopes I can deliver the next version on time.

The only change I made was to brighten up the Windsong Lyre a little, both to make it closer to the Oak Plank color, as well as further differentiation from the Vintage Lyre (especially when held in hand).  
I've also ever so slightly darkened the central area of the Zither, though ratherly unnoticeable.


> I think your way of doing the logo is fine lol.

Welp, then this would thus be the newly updated logo; wdyt?
<img src="https://github.com/StavWasPlayZ/Genshin-Instruments/assets/89315181/61d04e4c-4ea7-4256-90c2-119367ed5ee8?raw=true" width="100">


I'm rather unsure of this orientation, as it seems a bit crowded/messy to me... So I might rework it a little tomorrow :P


Nevertheless, looking forward to work with you more in the future ahead! 🙃

**Comment by GenMode** [comment]
ight let me know of any more instruments you want me to remake when you get to them

**Comment by StavWasPlayZ** [comment]
You may work on the [EMI textures](https://github.com/StavWasPlayZ/Even-More-Instruments/tree/1.20.1/src/main/resources/assets/evenmoreinstruments/textures/item), if you feel like it 😊

**Comment by GenMode** [comment]
ok I updated the other 16x16 instruments too. I'm going to be honest I kinda liked what you had so this wasn't much more than just a quick touch up. Hope you like it

![Screenshot 2023-09-19 190241](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/2d777a3c-4cb6-4f22-ae8b-1132a6ecbabc)

**Comment by GenMode** [comment]
![guitar](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/966e8d0b-d97d-45ee-bb20-91b786b08726)
![note_block_instrument](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/2d37af7c-4698-4467-bf7d-03a664d59e85)
![violin](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/787c16c3-c363-4033-9553-6d907ebeb3bc)

**Comment by StavWasPlayZ** [comment]
I opened this as a new issue under [#3](https://github.com/StavWasPlayZ/Even-More-Instruments/issues/3) in the EMI repository.

**Comment by GenMode** [comment]
ight

**Comment by StavWasPlayZ** [comment]
Ah and do make sure to subscribe to it because I doubt it is automatically done
![image](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/89315181/28f3dd8f-8e4e-4970-a506-1e71a36ed2cf)
